### ISSUE TITLE
Should url be transcribed?

### ISSUE THREAD

**Issue by ssoto** [andalugeeks/andaluh-py#12]
I did this tests:

``` python
import requests
from urllib.parse import urlencode

content = "Hola esto es una URL:    https://twitter.com/OficinaEspanol  Respetala porfa"
encoded_url_params = urlencode({"spanish": content})
response = requests.get(f"https://api.andaluh.es/epa?{encoded_url_params}")

response.json()
>  {'spanish': 'Hola esto es una URL:    https://twitter.com/OficinaEspanol  Respetala porfa',
>   'andaluh': 'Ola êtto êh una ÛL-L:    ttps://twîttêh.com/OfiçinaÊppanôh  Rêppetala porfa',
>  'rules': {'vaf': 'ç', 'vvf': 'h', 'escapeLinks': False}}
```

As you can see, transcription algorithm pass over url, appying rules and changing it.
Is this behaviour expected?

**Comment by fontanon** [comment]
Hi @ssoto please use `escapeLinks` url parameter to avoid transcribing URL. In other words: add `"escapeLinks": True` to your `encoded_url_params`

A curl example below: 

```
curl "https://api.andaluh.es/epa?spanish=Vente%20a%20https://andaluh.es%20a%20ver%20la%20p%C3%A1gina&vaf=s&vvf=j&escapeLinks=true"
```

Alos, please open issues related  with API into `andaluh-api` repo: https://github.com/andalugeeks/andaluh-api

**Comment by ssoto** [comment]
Sorry for being harder, did you see the transcription of `URL` to  `ÛL-L`? Let me know if this is a behaviour for `andaluh-api`. 
regards!

**Comment by penyaskito** [comment]
Looks like the regex is parsing only the first part of the url

`curl https://api.andaluh.es/epa?spanish=Vente%20a%20https://andaluh.es/esto/es/el/resto/de/una/url%20a%20ver%20la%20p%C3%A1gina&vaf=s&vvf=j&escapeLinks=true`

returns 

`{
spanish: "Vente a https://andaluh.es/esto/es/el/resto/de/una/url a ver la página",
andaluh: "Bente a https://andaluh.es/êtto/êh/el/rêtto/de/una/ûl-l a bêh la pájina",
rules: {
vaf: "s",
vvf: "j",
escapeLinks: true
}
} `

**Comment by fontanon** [comment]
Confirmed this behaviour with `andaluh-py`, reopening this issue.

```
$ python3
>>> import andaluh
>>> print(andaluh.epa("Hola esto es una URL:    https://twitter.com/OficinaEspanol  Respetala porfa", escape_links=True))
Ola êtto êh una ÛL-L:    https://twitter.com/OfiçinaÊppanôh  Rêppetala porfa
>>> 
```

**Comment by fontanon** [comment]
Related: https://github.com/andalugeeks/andaluh-api/issues/3

**Comment by fontanon** [comment]
> Sorry for being harder, did you see the transcription of `URL` to `ÛL-L`? Let me know if this behaviour is properly for `andaluh-api` or for `andaluh-py`.
> regards!

Please preceed with a hashtag those acronyms or foreign language words you do not want to be transcribed. The `andaluh-py` library just transcribes everything, it cannot be aware those situations.

**Comment by ssoto** [comment]
Thanks for your analysis guys!
Anyone is working on fix it? I can try fix it, I'm going to asing it to myself!

**Comment by fontanon** [comment]
I was already, was easy. Thanks.

**Comment by fontanon** [comment]
@ssoto @penyaskito please use `master` to test now.

https://github.com/andalugeeks/andaluh-py/commit/0e9a405d0e61028b7346908b7c0369c91a7b76be
