### ISSUE TITLE
Errôh al uçâh andalu en pyton 3.5.3

### ISSUE THREAD

**Issue by joseEnrique** [andalugeeks/andaluh-py#2]
El errôh que çale êh er çigiente al uçâh la libreria:

```
  File "/usr/local/lib/python3.5/dist-packages/andaluh/__init__.py", line 1, in <module>
    from lib import epa
ImportError: No module named 'lib' 
```

**Comment by FernanOrtega** [comment]
I'm afraid that this library only supports Python 2.7.

To support Python 3.x it needs to be updated in different ways, for example:

- print
- "ur" string prefix (https://bugs.python.org/issue15096)
- "exceptions" import
- rename file "lib.py" to another name

**Comment by ssoto** [comment]
I have created the PR  #3
I used `2to3` command. I made basic tests looks that it works nice.

**Comment by fontanon** [comment]
PR #3 fixes this issue.
