### ISSUE TITLE
Enable code gates (pytest and linter)

### ISSUE THREAD

**Issue by ssoto** [andalugeeks/andaluh-py#4]
In order to prevent  code changes that can breaks functionalities, enables pytest could be nice. I did a [PR in own fork](https://github.com/ssoto/andaluh-py/pull/1). This PR can't be merged until python3 has been implemented #3.

Once merged, we should enable automatic check when a PR is created in order to prevent (or minimize) bugs.

I think is a good idea to adopt [PEP8](https://www.python.org/dev/peps/pep-0008/) code standard in order to made standar code. I have used [Flake8 ](https://flake8.pycqa.org/en/latest/) I think could be enough. This integration have been [in my fork](https://github.com/ssoto/andaluh-py/pull/1)

What do you think about it?

**Comment by fontanon** [comment]
Hi @ssoto good job. This deserves to be merged. 

However, Is there any reason you're forcing python3.5.* instead of python3.6?

Can I suggest you submit a PR for python36 (editing tox and setup.py files)?

**Comment by ssoto** [comment]
Created #5. I think this PR should be done before in order to prevent broken changes.
